language: python

jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      python: 3.6
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      python: 3.6
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      python: 3.7

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest tests --cov cvma

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - flake8 --max-line-length 100
  - python -m pylint cvma/ tests/
  - python -m black --check cvma/ tests/

notification: false
