language: python

jobs:
  include:
    - name: "Python 3.6 and 3.7 on Xenial Linux"
      python:
        - "3.6"
        - "3.7"
      before_install:
        - pip3 install --upgrade pip
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install --upgrade pip
    - name: "Python 3.7.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.6

install:
  - pip install -r requirements.txt

script:
  - pytest tests --cov cvma

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - flake8 --max-line-length 100
  - python -m pylint cvma/ tests/
  - python -m black --check cvma/ tests/

notification: false
