language: python

jobs:
  allow_failures:
    - os: osx
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8 on MacOSX"
      stage: test
      os: osx
      language: sh
      env: TOXENV=py3
      addons:
        homebrew:
          packages: python3
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest tests --cov cvma

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - flake8 --max-line-length 100
  - python -m pylint cvma/ tests/
  - python -m black --check cvma/ tests/

notification: false
